version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: laliga
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=usuario
      - DB_PASSWORD=contraseña
      - DB_NAME=laliga

volumes:
  postgres_data: